apiVersion: batch/v1
kind: CronJob
metadata:
  name: secure-backup
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: backup
            image: alpine:3.14
            command: ["/bin/sh", "-c", "echo 'Backup task started at $(date)'; sleep 10; echo 'Backup completed'"]
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              runAsUser: 1000
              readOnlyRootFilesystem: true
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 128Mi
          restartPolicy: OnFailure