apiVersion: v1
kind: Pod
metadata:
  name: capabilities-pod
  labels:
    app: capabilities-example
spec:
  containers:
  - name: network-tools
    image: alpine:latest
    command: ["sleep", "infinity"]
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "NET_RAW"]
      runAsUser: 1000
      allowPrivilegeEscalation: true