apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  labels:
    app: hostpath-example
spec:
  containers:
  - name: webserver
    image: nginx:latest
    volumeMounts:
    - name: host-data
      mountPath: /data
    securityContext:
      runAsUser: 1000
  volumes:
  - name: host-data
    hostPath:
      path: /var/data
      type: Directory