apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-admin
  namespace: development
rules:
- apiGroups: ["", "apps", "batch", "extensions"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-admin-binding
  namespace: development
subjects:
- kind: User
  name: developer-admin
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: cicd-pipeline
  namespace: development
roleRef:
  kind: Role
  name: namespace-admin
  apiGroup: rbac.authorization.k8s.io