kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dangerous-resource-wildcard
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["update", "patch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["create", "delete"]