kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: high-danger-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["delete", "create"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "deletecollection"]