kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mixed-severity-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete", "patch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "update", "delete"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles"]
  verbs: ["escalate", "bind"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["*"]