kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dangerous-role-1
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete"]
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dangerous-role-2
  namespace: kube-system
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["bind", "escalate"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dangerous-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["secrets"]
  verbs: ["*"]