apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: super-privileged
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: super-privileged-binding
subjects:
- kind: ServiceAccount
  name: automation-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: super-privileged
  apiGroup: rbac.authorization.k8s.io