apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user-impersonator
rules:
- apiGroups: [""]
  resources: ["users", "groups", "serviceaccounts"]
  verbs: ["impersonate"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: impersonation-binding
subjects:
- kind: ServiceAccount
  name: support-account
  namespace: support
roleRef:
  kind: ClusterRole
  name: user-impersonator
  apiGroup: rbac.authorization.k8s.io